<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputPath>..\1.5\Assemblies</OutputPath>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>HSKMechShipPower</AssemblyName>
    <AssemblyTitle>HSKMechShipPower</AssemblyTitle>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <RootNamespace>HSKMechShipPower</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony">
      <Version>2.3.1.1</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Rimworld.Ref">
      <Version>[1.5.4297.0]</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
